### ISSUE TITLE
[BUG] : timeline breaks in mobile view

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/programming-language-timeline-website#13]
### ✏️ Describe the bug

when view width is less than 400px i.e mobile view the timeline alignment becomes zig-zag 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/83657737/198877782-cd66d652-cd50-47de-b3f8-413f3182fff0.png)

**Comment by amitanshusahu** [comment]
i would like to work on this

**Comment by osbc2022** [comment]
go for it :star_struck:
