### ISSUE TITLE
[FEAT] : Adding animation and hover effects

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/programming-language-timeline-website#14]
### ✏️ Description

the site isn't much interactive , we can add animations and hover effects to it

**Comment by osbc2022** [comment]
go for it

**Comment by karthykarthick** [comment]
@osbc2022, @amitanshusahu   can i try this
can we change the languages to Upper case it is my suggestion because currently there is a combination of smaller case and uppercase

**Comment by osbc2022** [comment]
@karthykarthick  , :star_struck:  you can create a new issue for that.. i will assign it to you.. 
> Note :- there are other incomplete projects to which you can contribute.. :heart_eyes:

**Comment by karthykarthick** [comment]
@osbc2022 sure i will do that can you share other projects as well I am happy to contribute ❤️

**Comment by osbc2022** [comment]
> - @karthykarthick , you can contribute to any repo here :- https://github.com/osbc2022
