### ISSUE TITLE
[FEAT] :  Change All Languages to Uppercase

### ISSUE THREAD

**Issue by karthykarthick** [osbc2022/programming-language-timeline-website#15]
### ✏️ Description

Currently there is a Mixed of smaller case and Uppercase are used For displaying languages I'd like to change this to Uppercase 

### 📸 Screenshots

NA

**Comment by karthykarthick** [comment]
@osbc2022  Can you assign this to me

**Comment by osbc2022** [comment]
go for it @karthykarthick  :heart_eyes:
