### ISSUE TITLE
[BREAK THROUGH] : changing the ui of the website

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/programming-language-timeline-website#2]
### ✏️ Description

the website looks very basic , the ui can be updated with content cards 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/83657737/198729454-6456cde6-fb17-454a-b66e-7260f05eeb16.png)

**Comment by amitanshusahu** [comment]
i would like to work on this

**Comment by osbc2022** [comment]
:heart_eyes: yeah go for it
