### ISSUE TITLE
[DOCS] : wrong description in readme

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/programming-language-timeline-website#3]
### ✏️ Description

the `readme.md` has wrong description of the website , it is of the to-do-website , but it should be of timeline website

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/83657737/198730394-382f950f-4b6d-40a8-90d8-f4d844aa7951.png)

**Comment by amitanshusahu** [comment]
i would like to work on this

**Comment by osbc2022** [comment]
go for it :+1:
