### ISSUE TITLE
[BUG] : updating the content dynamically

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/programming-language-timeline-website#7]
### ✏️ Describe the bug

the timeline cards can be updated dynamically with the help of javascript which will make it more mannageble. 
- a array of object with date, heading, description can be made
- then each array can be mapped into html elements and can be rendered with .innerHTML

**Comment by osbc2022** [comment]
Awesome :heart_eyes:  go for it,  @amitanshusahu
