### ISSUE TITLE
[DOCS] : add a contribution section in the read me

### ISSUE THREAD

**Issue by osbc2022** [osbc2022/programming-language-timeline-website#9]
### ✏️ Description

To do :-

- [ ] add a contribution section in the readme
- [ ] list all of our contributors in there using the github api
- [ ] align everything in the center

>    Note : - use can use contrib.rocks generated image url for this

``` html
<a href="https://github.com/osbc2022/to-do-list/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=osbc2022/to-do-list" />
</a>
```

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/115569958/198834728-9e2b806c-4ab7-42d9-b703-405c7ed7f6f6.png)

**Comment by karthykarthick** [comment]
can  u assign me on this
